version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb_container
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: destinations
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rodrigoperez
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123456
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  app:
    build: .
    container_name: node_app
    restart: always
    ports:
      - '3002:3002'
    depends_on:
      - mongodb
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}

      MONGO_USER: rodrigoperez
      MONGO_PASS: 123456
      MONGO_DB_NAME: destinations
      JWT_SECRET: dev_secret_key
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: yarn dev

volumes:
  mongo_data:
